[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
# opt-level = "s"
lto = "thin"

[workspace.dependencies]
noitad-lib = { path = "crates/noitad-lib" }

eyre = "0.6"
color-eyre = "0.6"
