on:
  push:
    paths: ["**.rs"]
  pull_request:
    paths: ["**.rs"]
  workflow_dispatch:

name: Linux Build

env:
  # This is required to enable the web_sys clipboard API which egui_web uses
  # https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html
  # https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
  RUSTFLAGS: --cfg=web_sys_unstable_apis
  CARGO_TERM_COLOR: always

jobs:
  linux_gnu_build:
    name: Linux GNU Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-linux-gnu
      - name: Setup device_query dependencies
        run: sudo apt-get install libx11-dev
      - name: Setup rdev dependencies
        run: sudo apt-get --assume-yes install libxtst-dev libevdev-dev
      - name: Setup eframe dependencies
        run: sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev
      - name: Build
        run: cargo build -p noitad-cli --verbose --target x86_64-unknown-linux-gnu
