on:
  push:
    paths: ["**.rs"]
  pull_request:
    paths: ["**.rs"]
  workflow_dispatch:

name: macOS Build

env:
  # This is required to enable the web_sys clipboard API which egui_web uses
  # https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html
  # https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
  RUSTFLAGS: --cfg=web_sys_unstable_apis
  CARGO_TERM_COLOR: always

jobs:
  apple_darwin_build:
    name: Apple Darwin Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-apple-darwin
      - name: Build
        run: cargo build --verbose --target x86_64-apple-darwin
