name: Build and release
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    uses: ./.github/workflows/build_artifacts.yml
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Downloads artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin
      - name: Creating draft release
        # if: startsWith(github.ref, 'refs/tags/') # limit releases to tags
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*/noitad-*
          draft: true
